logging:
  level:
    root: warn
    com.labmj.scheduler: info
  path: /home/ec2-user/api/log
  file:
    max-history: 7
spring:
  profiles: alpha
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:mysql://dburl:3306/dbname?useUnicode=true&amp;autoReconnect=true&amp;characterEncoding=utf8&amp;allowMultiQueries=true&amp;useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: jkh
    password: secret
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties.hibernate:
      hbm2ddl.auto: none
      format_sql: true
    showSql: true
    generate-ddl: false
  messages:
    basename: i18n/exception
    encoding: UTF-8
  url:
    base: http://jkh.com

